image: node:13.11.0

cache:
  paths:
  - node_modules/

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DEPLOY_HOST: 'root@$DEPLOY_SSH_SERVER'
  PORT: 3000

before_script:
  - echo "Before script..."
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.
  
build:
  stage: build
  script:
    - echo "Initialize build task..."
    - "docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - "docker build -t $IMAGE_NAME ."
    - "docker push $IMAGE_NAME"
    - echo "Finalized build task..."

deploy:
  stage: deploy
  script:
    - ssh DEPLOY_HOST "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker pull $IMAGE_NAME; docker run -p $PORT:$PORT -d $IMAGE_NAME"