image: node:13.11.0
pipelines:
  default:
  - step:
      name: Build and Test
      caches:
      - node
      script:
      - node --version
      - npm install
      - npm run dev

  branches:
    master:
    - step:
        name: Deploy to Registry
        services:
        - docker
        script:
        - export IMAGE_NAME=blackinitial/blackinitial-site:$BITBUCKET_COMMIT
        - docker build -t $IMAGE_NAME .
        - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
        - docker push $IMAGE_NAME
        
    - step:
        name: Deploy to Digital Ocean
        services:
        - docker
        script:
        - export IMAGE_NAME=blackinitial/blackinitial-site:$BITBUCKET_COMMIT
        - pipe: atlassian/ssh-run:0.2.2
          variables:
            SSH_USER: $SSH_USER
            SERVER: $SSH_SERVER
            COMMAND: >
              docker stop $CONTAINERS_TO_STOP
              docker run -p $SERVER_PORT:$SERVER_PORT -d $IMAGE_NAME